openapi: 3.0.0
info:
  title: Digital Twin Simulation Content API
  description: API for accessing educational content about Gazebo and Unity simulation
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server

paths:
  /modules/digital-twin-sim:
    get:
      summary: Get Digital Twin Simulation module information
      description: Retrieve metadata about the Digital Twin Simulation module
      responses:
        '200':
          description: Module information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Module'

  /modules/digital-twin-sim/chapters:
    get:
      summary: Get all chapters in Digital Twin Simulation module
      description: Retrieve a list of all chapters in the module
      responses:
        '200':
          description: List of chapters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chapter'

  /modules/digital-twin-sim/chapters/{chapterId}:
    get:
      summary: Get specific chapter content
      description: Retrieve content of a specific chapter by ID
      parameters:
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
            enum: [physics-simulation-gazebo, sensors-in-simulation, high-fidelity-digital-twins]
          description: ID of the chapter to retrieve
      responses:
        '200':
          description: Chapter content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chapter'
        '404':
          description: Chapter not found

components:
  schemas:
    Module:
      type: object
      required:
        - id
        - name
        - description
        - chapters
      properties:
        id:
          type: string
          example: "digital-twin-sim"
        name:
          type: string
          example: "Digital Twin Simulation"
        description:
          type: string
          example: "Teaching physics-based simulation and digital twins for humanoid robots using Gazebo and Unity"
        target_audience:
          type: string
          example: "AI students familiar with basic ROS concepts"
        chapters:
          type: array
          items:
            $ref: '#/components/schemas/Chapter'

    Chapter:
      type: object
      required:
        - id
        - title
        - content
        - learning_objectives
      properties:
        id:
          type: string
          example: "physics-simulation-gazebo"
        title:
          type: string
          example: "Physics Simulation with Gazebo"
        sidebar_label:
          type: string
          example: "Physics Simulation"
        description:
          type: string
          example: "Understanding physics-based simulation using Gazebo for humanoid robots"
        content:
          type: string
          description: Markdown content of the chapter
          example: "# Physics Simulation with Gazebo\n\nGazebo is a physics-based simulation environment..."
        learning_objectives:
          type: array
          items:
            type: string
          example: ["Understand the role of simulation in robotics", "Configure gravity and collision parameters", "Simulate humanoid environments"]
        prerequisites:
          type: array
          items:
            type: string
          example: ["Basic ROS concepts"]
        next_chapter:
          type: string
          example: "sensors-in-simulation"