import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for our AI-Driven Technical Book
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'ROS 2 Nervous System',
      items: [
        'modules/ros2-nervous-system/intro-to-ros2',
        'modules/ros2-nervous-system/ros2-communication',
        'modules/ros2-nervous-system/robot-structure-basics',
      ],
    },
    {
      type: 'category',
      label: 'Digital Twin Simulation',
      items: [
        'modules/digital-twin-sim/physics-simulation-gazebo',
        'modules/digital-twin-sim/sensors-in-simulation',
        'modules/digital-twin-sim/high-fidelity-digital-twins',
      ],
    },
    {
      type: 'category',
      label: 'AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'modules/ai-robot-brain-isaac/nvidia-isaac-sim',
        'modules/ai-robot-brain-isaac/isaac-ros-perception',
        'modules/ai-robot-brain-isaac/nav2-navigation',
      ],
    },
    {
      type: 'category',
      label: 'Vision-Language-Action (VLA) Systems',
      items: [
        'modules/vision-language-action/voice-to-action',
        'modules/vision-language-action/cognitive-planning',
        'modules/vision-language-action/autonomous-humanoid',
      ],
    },
  ],
};

export default sidebars;
